#!/bin/bash -e

#
# Copyright (C) 2016 Canonical Ltd
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# check if we have enough interfaces connected to start dockerd

# check if enough interfaces is connected to start dockerd
# as minimum we want, docker-support, firewall-control, and home

if snapctl is-connected firewall-control && \
   snapctl is-connected home ; then
     snapctl start --enable ${SNAP_INSTANCE_NAME}.dockerd
fi